compile:
  # Choosing to run compilation tests on 2 different Arduino platforms
  platforms:
    - uno
    - leonardo
    - due
    - zero
  libraries:
    - "SoftwareSerial"

unittest:
  # These dependent libraries will be installed
  libraries:
    
    
    
    
